version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"